In [ ]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../data/processed/base_de_dados_completo_eda.csv')

## Exploração inicial

In [4]:
df.head()

,data_referencia,ra,fase,turma,nome,ano_nasc,idade_22,gênero,ano_ingresso,instituição_de_ensino,...,ing,fase_ideal.1,destaque_ipv_1,inde_2024,pedra_2024,avaliador5,avaliador6,escola,ativo/inativo,ativo/inativo_1
0,2022-01-01,RA-1,7,A,Aluno-1,2003.0,19.0,Menina,2016,Escola Pública,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-01,RA-61,5,B,Aluno-61,2007.0,15.0,Menino,2021,Escola Pública,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01-01,RA-610,1,L,Aluno-610,2013.0,9.0,Menina,2022,Escola Pública,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-01-01,RA-611,1,M,Aluno-611,2010.0,12.0,Menino,2021,Escola Pública,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-01-01,RA-612,1,M,Aluno-612,2012.0,10.0,Menina,2021,Escola Pública,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.query('ra == "RA-1000"')

,data_referencia,ra,fase,turma,nome,ano_nasc,idade_22,gênero,ano_ingresso,instituição_de_ensino,...,ing,fase_ideal.1,destaque_ipv_1,inde_2024,pedra_2024,avaliador5,avaliador6,escola,ativo/inativo,ativo/inativo_1
1529,2023-01-01,RA-1000,ALFA,ALFA U - G2/G3,NaN,NaN,NaN,Feminino,2023,Pública,...,NaN,ALFA (1° e 2° ano),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2644,2024-01-01,RA-1000,1N,1N,NaN,NaN,NaN,Feminino,2023,Pública,...,NaN,Fase 1 (3° e 4° ano),NaN,8.364790909100002,Topázio,NaN,NaN,EE Helio Luiz Dobrochinski Prof,Cursando,Cursando

In [6]:
df_pivot = (
    df
    .set_index(["ra", "data_referencia"])
    .unstack("data_referencia")
)

# display(df_pivot.columns)
# achata o MultiIndex das colunas
df_pivot.columns = [f"{col}_{ano}" for col, ano in df_pivot.columns]

df_pivot = df_pivot.reset_index()

df_pivot.head()

,ra,fase_2022-01-01,fase_2023-01-01,fase_2024-01-01,turma_2022-01-01,turma_2023-01-01,turma_2024-01-01,nome_2022-01-01,nome_2023-01-01,nome_2024-01-01,...,avaliador6_2024-01-01,escola_2022-01-01,escola_2023-01-01,escola_2024-01-01,ativo/inativo_2022-01-01,ativo/inativo_2023-01-01,ativo/inativo_2024-01-01,ativo/inativo_1_2022-01-01,ativo/inativo_1_2023-01-01,ativo/inativo_1_2024-01-01
0,RA-1,7,FASE 8,8E,A,8E,8E,Aluno-1,NaN,NaN,...,NaN,NaN,NaN,Universidade Santo Amaro (UNISA),NaN,NaN,Cursando,NaN,NaN,Cursando
1,RA-10,7,NaN,NaN,A,NaN,NaN,Aluno-10,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RA-100,4,NaN,NaN,A,NaN,NaN,Aluno-100,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RA-1000,NaN,ALFA,1N,NaN,ALFA U - G2/G3,1N,NaN,NaN,NaN,...,NaN,NaN,NaN,EE Helio Luiz Dobrochinski Prof,NaN,NaN,Cursando,NaN,NaN,Cursando
4,RA-1001,NaN,ALFA,1N,NaN,ALFA U - G2/G3,1N,NaN,NaN,NaN,...,NaN,NaN,NaN,EE Helio Luiz Dobrochinski Prof,NaN,NaN,Cursando,NaN,NaN,Cursando

In [7]:
df_pivot[df_pivot.columns[df_pivot.columns.str.contains('fase')]]

,fase_2022-01-01,fase_2023-01-01,fase_2024-01-01,fase_ideal_2022-01-01,fase_ideal_2023-01-01,fase_ideal_2024-01-01,fase_ideal.1_2022-01-01,fase_ideal.1_2023-01-01,fase_ideal.1_2024-01-01
0,7,FASE 8,8E,Fase 8 (Universitários),NaN,NaN,NaN,Fase 8 (Universitários),Fase 8 (Universitários)
1,7,NaN,NaN,Fase 8 (Universitários),NaN,NaN,NaN,NaN,NaN
2,4,NaN,NaN,Fase 3 (7º e 8º ano),NaN,NaN,NaN,NaN,NaN
3,NaN,ALFA,1N,NaN,NaN,NaN,NaN,ALFA (1° e 2° ano),Fase 1 (3° e 4° ano)
4,NaN,ALFA,1N,NaN,NaN,NaN,NaN,Fase 1 (3° e 4° ano),Fase 2 (5° e 6° ano)
...,...,...,...,...,...,...,...,...,...
1656,NaN,ALFA,1E,NaN,NaN,NaN,NaN,Fase 2 (5° e 6° ano),Fase 3 (7° e 8° ano)
1657,NaN,ALFA,NaN,NaN,NaN,NaN,NaN,Fase 1 (3° e 4° ano),NaN
1658,NaN,ALFA,NaN,NaN,NaN,NaN,NaN,ALFA (1° e 2° ano),NaN
1659,NaN,ALFA,NaN,NaN,NaN,NaN,NaN,Fase 2 (5° e 6° ano),NaN
1660,NaN,ALFA,NaN,NaN,NaN,NaN,NaN,Fase 1 (3° e 4° ano),NaN

In [13]:
df_pivot[df_pivot['fase_2024-01-01'].isna()].head()
# Alunos com fase_2024-01-01 vazia não aparecem na base de 2024

,ra,fase_2022-01-01,fase_2023-01-01,fase_2024-01-01,turma_2022-01-01,turma_2023-01-01,turma_2024-01-01,nome_2022-01-01,nome_2023-01-01,nome_2024-01-01,...,avaliador6_2024-01-01,escola_2022-01-01,escola_2023-01-01,escola_2024-01-01,ativo/inativo_2022-01-01,ativo/inativo_2023-01-01,ativo/inativo_2024-01-01,ativo/inativo_1_2022-01-01,ativo/inativo_1_2023-01-01,ativo/inativo_1_2024-01-01
1,RA-10,7,NaN,NaN,A,NaN,NaN,Aluno-10,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RA-100,4,NaN,NaN,A,NaN,NaN,Aluno-100,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,RA-1005,NaN,ALFA,NaN,NaN,ALFA V - G0/G1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,RA-1007,NaN,ALFA,NaN,NaN,ALFA V - G0/G1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,RA-101,4,NaN,NaN,A,NaN,NaN,Aluno-101,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_pivot["fase_2024-01-01"].unique()

<ArrowStringArray>
[  '8E',    nan,   '1N', 'ALFA',   '2B',   '2C',   '1A',   '1B',   '1C',
   '5A',   '2D',   '2H',   '2I',   '1H',   '2G',   '2A',   '1J',   '1L',
   '1K',   '2M',   '6A',   '2N',   '2L',   '2R',   '2K',   '5D',   '1P',
   '3B',   '3A',   '3D',   '4C',   '3C',   '3G',   '3H',   '3F',   '5B',
   '3I',   '3M',   '3K',   '3N',   '5G',   '3U',   '3R',   '3P',   '2P',
   '3L',   '4A',   '4F',   '4M',   '4N',   '4R',   '5C',   '5F',   '7E',
   '4L',   '5N',   '6L',   '5M',   '7A',   '8F',    '9',   '8A',   '8B',
   '8D',   '1D',   '1E',   '1G',   '1M',   '1R',   '2U',   '5L',   '4B',
   '4H']
Length: 73, dtype: str

### Normalização fase (apenas 2024)

In [28]:
def normaliza_fase(fase):
    if pd.isna(fase):
        return fase
    
    if fase.lower() == 'alfa':
        return 0
    
    return fase[0]

In [31]:
df_pivot['fase_2024'] = df_pivot["fase_2024-01-01"].apply(normaliza_fase)
# valore NaN nessa coluna significam que o aluno não estava na base de 2024

In [32]:
df_pivot.head()

,ra,fase_2022-01-01,fase_2023-01-01,fase_2024-01-01,turma_2022-01-01,turma_2023-01-01,turma_2024-01-01,nome_2022-01-01,nome_2023-01-01,nome_2024-01-01,...,escola_2022-01-01,escola_2023-01-01,escola_2024-01-01,ativo/inativo_2022-01-01,ativo/inativo_2023-01-01,ativo/inativo_2024-01-01,ativo/inativo_1_2022-01-01,ativo/inativo_1_2023-01-01,ativo/inativo_1_2024-01-01,fase_2024
0,RA-1,7,FASE 8,8E,A,8E,8E,Aluno-1,NaN,NaN,...,NaN,NaN,Universidade Santo Amaro (UNISA),NaN,NaN,Cursando,NaN,NaN,Cursando,8
1,RA-10,7,NaN,NaN,A,NaN,NaN,Aluno-10,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RA-100,4,NaN,NaN,A,NaN,NaN,Aluno-100,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RA-1000,NaN,ALFA,1N,NaN,ALFA U - G2/G3,1N,NaN,NaN,NaN,...,NaN,NaN,EE Helio Luiz Dobrochinski Prof,NaN,NaN,Cursando,NaN,NaN,Cursando,1
4,RA-1001,NaN,ALFA,1N,NaN,ALFA U - G2/G3,1N,NaN,NaN,NaN,...,NaN,NaN,EE Helio Luiz Dobrochinski Prof,NaN,NaN,Cursando,NaN,NaN,Cursando,1

## Perguntas a serem respondidas Tech 5

### 1. Adequação do nível (IAN): Qual é o perfil geral de defasagem dos alunos (IAN) e como ele evolui ao longo do ano?

### 2. Desempenho acadêmico (IDA): O desempenho acadêmico médio (IDA) está melhorando, estagnado ou caindo ao longo das fases e anos?

### 3. Engajamento nas atividades (IEG): O grau de engajamento dos alunos (IEG) tem relação direta com seus indicadores de desempenho (IDA) e do ponto de virada (IPV)?

### 4. Autoavaliação (IAA): As percepções dos alunos sobre si mesmos (IAA) são coerentes com seu desempenho real (IDA) e engajamento (IEG)?