In [56]:
# Libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from pathlib import Path

## Configuração para apresentar todas as colunas do dataframe

In [57]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

## Defini caminho do arquivo

In [58]:
arquivo_excel = (
    Path.cwd()
    .parents[1] / 'data' / 'raw' / 'BASE_DE_DADOS_PEDE_2024_DATATHON.xlsx'
)

assert arquivo_excel.exists(), "❌ Arquivo Excel não encontrado"
print("✅ Arquivo encontrado:", arquivo_excel.name)

✅ Arquivo encontrado: BASE_DE_DADOS_PEDE_2024_DATATHON.xlsx

## Carrega as planilhas e adiciona coluna de ano de referência

In [59]:
excel_file = pd.ExcelFile(arquivo_excel)

df1 = pd.read_excel(arquivo_excel, sheet_name='PEDE2022')
df2 = pd.read_excel(arquivo_excel, sheet_name='PEDE2023')
df3 = pd.read_excel(arquivo_excel, sheet_name='PEDE2024')

print("📊 Shapes:")
print("PEDE2022:", df1.shape)
print("PEDE2023:", df2.shape)
print("PEDE2024:", df3.shape)

df1['ano_referencia'] = 2022
df2['ano_referencia'] = 2023
df3['ano_referencia'] = 2024

📊 Shapes:
PEDE2022: (860, 42)
PEDE2023: (1014, 48)
PEDE2024: (1156, 50)

## Empilhamento vertical

In [60]:
df_final = pd.concat(
    [df1, df2, df3],
    axis=0,
    ignore_index=True,
    sort=False
)

print("✅ Dataset empilhado com sucesso")
print("Shape final:", df_final.shape)

✅ Dataset empilhado com sucesso
Shape final: (3030, 63)

## Cria coluna de data

In [61]:
df_final.insert(
    0,
    'data_referencia',
    pd.to_datetime(df_final['ano_referencia'], format='%Y', errors='coerce')
)

## Ordena cronologicamente

In [62]:
df_final = (
    df_final
    .sort_values('data_referencia')
    .reset_index(drop=True)
)

## Validação

In [63]:
print("\n🔎 Verificação temporal:")
print(df_final[['ano_referencia', 'data_referencia']].drop_duplicates().sort_values('ano_referencia'))

print("\n📈 Registros por ano:")
print(df_final['ano_referencia'].value_counts().sort_index())

🔎 Verificação temporal:
      ano_referencia data_referencia
0               2022      2022-01-01
860             2023      2023-01-01
1874            2024      2024-01-01

📈 Registros por ano:
ano_referencia
2022     860
2023    1014
2024    1156
Name: count, dtype: int64

In [64]:
df_final.head()

,data_referencia,RA,Fase,Turma,Nome,Ano nasc,Idade 22,Gênero,Ano ingresso,Instituição de ensino,Pedra 20,Pedra 21,Pedra 22,INDE 22,Cg,Cf,Ct,Nº Av,Avaliador1,Rec Av1,Avaliador2,Rec Av2,Avaliador3,Rec Av3,Avaliador4,Rec Av4,IAA,IEG,IPS,Rec Psicologia,IDA,Matem,Portug,Inglês,Indicado,Atingiu PV,IPV,IAN,Fase ideal,Defasagem,Destaque IEG,Destaque IDA,Destaque IPV,ano_referencia,INDE 2023,Pedra 2023,Nome Anonimizado,Data de Nasc,Idade,Pedra 23,INDE 23,IPP,Mat,Por,Ing,Fase Ideal,Destaque IPV.1,INDE 2024,Pedra 2024,Avaliador5,Avaliador6,Escola,Ativo/ Inativo,Ativo/ Inativo.1
0,2022-01-01,RA-1,7,A,Aluno-1,2003.0,19.0,Menina,2016,Escola Pública,Ametista,Ametista,Quartzo,5.783,753.0,18.0,10.0,4.0,Avaliador-5,Mantido na Fase atual,Avaliador-27,Promovido de Fase + Bolsa,Avaliador-28,Promovido de Fase,Avaliador-31,Mantido na Fase atual,8.3,4.1,5.6,Requer avaliação,4.0,2.7,3.5,6.0,Sim,Não,7.278,5.0,Fase 8 (Universitários),-1,Melhorar: Melhorar a sua entrega de lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliações.,Melhorar: Integrar-se mais aos Princípios Passos Mágicos.,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-01,RA-61,5,B,Aluno-61,2007.0,15.0,Menino,2021,Escola Pública,NaN,Ágata,Ametista,7.533,298.0,20.0,8.0,3.0,Avaliador-5,Mantido na Fase atual,Avaliador-27,Mantido na Fase atual,Avaliador-24,Promovido de Fase + Bolsa,Avaliador-31,NaN,9.2,7.4,7.5,Não atendido,5.8,1.7,6.3,9.3,Sim,Não,7.875,10.0,Fase 5 (1º EM),0,Melhorar: Melhorar a sua entrega de lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliações.,Destaque: A sua boa integração aos Princípios Passos Mágicos.,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01-01,RA-610,1,L,Aluno-610,2013.0,9.0,Menina,2022,Escola Pública,NaN,NaN,Topázio,8.180,91.0,21.0,3.0,3.0,Avaliador-4,Mantido na Fase atual,Avaliador-2,Promovido de Fase,NaN,Mantido na Fase atual,NaN,NaN,9.0,9.6,7.5,Sem limitações,6.5,6.0,7.0,NaN,Não,Sim,8.500,10.0,Fase 1 (4º ano),0,Destaque: A sua boa entrega das lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliações.,Destaque: A sua boa integração aos Princípios Passos Mágicos.,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-01-01,RA-611,1,M,Aluno-611,2010.0,12.0,Menino,2021,Escola Pública,NaN,Ametista,Ametista,7.756,214.0,54.0,4.0,3.0,Avaliador-7,Promovido de Fase + Bolsa,Avaliador-3,Promovido de Fase,NaN,Promovido de Fase,NaN,NaN,9.5,7.6,7.5,Não atendido,9.5,10.0,9.0,NaN,Sim,Não,7.556,5.0,Fase 3 (7º e 8º ano),-2,Destaque: A sua boa entrega das lições de casa.,Destaque: As suas boas notas na Passos Mágicos.,Destaque: A sua boa integração aos Princípios Passos Mágicos.,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-01-01,RA-612,1,M,Aluno-612,2012.0,10.0,Menina,2021,Escola Pública,NaN,Topázio,Ametista,7.594,273.0,71.0,6.0,3.0,Avaliador-7,Promovido de Fase,Avaliador-3,Mantido na Fase atual,NaN,Mantido na Fase atual,NaN,NaN,9.0,9.2,7.5,Não atendido,7.9,9.7,6.2,NaN,Não,Não,7.167,5.0,Fase 2 (5º e 6º ano),-1,Destaque: A sua boa entrega das lições de casa.,Destaque: As suas boas notas na Passos Mágicos.,Melhorar: Integrar-se mais aos Princípios Passos Mágicos.,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Tratamentos e Padronização do dataset

In [65]:
# Renomeia as colunas no padrão snake case

def renomeia_colunas(df):
    '''
        Função responsavel por renomear colunas 
        no padrão snake case (nome_coluna)

        Parametros:
        Inserir o dataframe como paramêtro
    '''
    column_name = df.columns

    coluna_tratada = {}

    for coluna in column_name:
        #print(coluna)
        col = coluna.replace("/ ", "/").replace(" ", "_").replace(".","_").lower()
        coluna_tratada[coluna] = col
    
    coluna_tratada = df_final.columns.map(coluna_tratada)
    df.columns = coluna_tratada
    
    return df

In [ ]:
df_final = renomeia_colunas(df_final)
df_final.head(1)

In [70]:
df_final.head(3)

,data_referencia,ra,fase,turma,nome,ano_nasc,idade_22,gênero,ano_ingresso,instituição_de_ensino,pedra_20,pedra_21,pedra_22,inde_22,cg,cf,ct,nº_av,avaliador1,rec_av1,avaliador2,rec_av2,avaliador3,rec_av3,avaliador4,rec_av4,iaa,ieg,ips,rec_psicologia,ida,matem,portug,inglês,indicado,atingiu_pv,ipv,ian,fase_ideal,defasagem,destaque_ieg,destaque_ida,destaque_ipv,ano_referencia,inde_2023,pedra_2023,nome_anonimizado,data_de_nasc,idade,pedra_23,inde_23,ipp,mat,por,ing,fase_ideal,destaque_ipv_1,inde_2024,pedra_2024,avaliador5,avaliador6,escola,ativo/inativo,ativo/inativo_1
0,2022-01-01,RA-1,7,A,Aluno-1,2003.0,19.0,Menina,2016,Escola Pública,Ametista,Ametista,Quartzo,5.783,753.0,18.0,10.0,4.0,Avaliador-5,Mantido na Fase atual,Avaliador-27,Promovido de Fase + Bolsa,Avaliador-28,Promovido de Fase,Avaliador-31,Mantido na Fase atual,8.3,4.1,5.6,Requer avaliação,4.0,2.7,3.5,6.0,Sim,Não,7.278,5.0,Fase 8 (Universitários),-1,Melhorar: Melhorar a sua entrega de lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliações.,Melhorar: Integrar-se mais aos Princípios Passos Mágicos.,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-01,RA-61,5,B,Aluno-61,2007.0,15.0,Menino,2021,Escola Pública,NaN,Ágata,Ametista,7.533,298.0,20.0,8.0,3.0,Avaliador-5,Mantido na Fase atual,Avaliador-27,Mantido na Fase atual,Avaliador-24,Promovido de Fase + Bolsa,Avaliador-31,NaN,9.2,7.4,7.5,Não atendido,5.8,1.7,6.3,9.3,Sim,Não,7.875,10.0,Fase 5 (1º EM),0,Melhorar: Melhorar a sua entrega de lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliações.,Destaque: A sua boa integração aos Princípios Passos Mágicos.,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01-01,RA-610,1,L,Aluno-610,2013.0,9.0,Menina,2022,Escola Pública,NaN,NaN,Topázio,8.180,91.0,21.0,3.0,3.0,Avaliador-4,Mantido na Fase atual,Avaliador-2,Promovido de Fase,NaN,Mantido na Fase atual,NaN,NaN,9.0,9.6,7.5,Sem limitações,6.5,6.0,7.0,NaN,Não,Sim,8.500,10.0,Fase 1 (4º ano),0,Destaque: A sua boa entrega das lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliações.,Destaque: A sua boa integração aos Princípios Passos Mágicos.,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Salva dataframe na pasta data/processed para EDA

In [71]:
df_final.to_csv("../../data/processed/base_de_dados_completo_eda.csv", index=False)